version: '3.6'

services:

# Database storage
  postgres-resources:
    image: postgres:14
    volumes:
      - "postgres-resource-service-vol:/var/lib/postgresql/data"
      - "./docker-compose/postgres:/docker-entrypoint-initdb.d/"

    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - resource-network

# Resource service for file manipulation
  resource-service:
    image: resource-service-local-image
    build:
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres-resources
    networks:
      - resource-network

volumes:
  postgres-resource-service-vol:
    driver: local

networks:
  resource-network:
    external: true
    driver: bridge