version: '3.6'

services:
#  AWS Cloud storage simulation
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    volumes:
      - "localstack-vol:/tmp/localstack/data"
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=test
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DATA_DIR=/tmp/localstack/data
    networks:
      - resource-network

# Database storage
  postgres:
    container_name: postgres_db
    image: postgres:14
    volumes:
      - "postgres-resource-service-vol:/var/lib/postgresql/data"
      - "./postgres:/docker-entrypoint-initdb.d/"

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    networks:
      - resource-network

volumes:
  postgres-resource-service-vol:
    driver: local
  localstack-vol:

networks:
  resource-network:
    external: true
    driver: bridge